### ISSUE TITLE
key error 'ProcessId' python error code

### ISSUE THREAD

**Issue by shuklaavantika** [Copyleaks/Python-Plagiarism-Checker#9]
I am getting this error whenever i am testing to upload my local file, please help
```python
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Avantika Shukla\Documents\Flask Project\app.py", line 50, in plagcheck
    process = cloud.createByFile(path,options=options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\copyleaks\copyleakscloud.py", line 147, in createByFile
    return CopyleaksProcess(self.getProduct(), self.token, response.json())
  File "C:\ProgramData\Anaconda3\lib\site-packages\copyleaks\copyleaksprocess.py", line 48, in __init__
    self.PID = infoDict['ProcessId']
KeyError: 'ProcessId'
```
my code 
```python
 cloud = CopyleaksCloud(Product.Education, 'avantikashuklaas07@gmail.com', 'MY API KEY')# You can change the product.
   print("You've got %s Copyleaks %s API credits" % (cloud.getCredits(), cloud.getProduct())) #get credit balance

   options = ProcessOptions()
   options.setSandboxMode(True)  # Scan will not consume any credits and will return dummy results.  
   options.setHttpCallback("http://requestb.in")
   process = cloud.createByFile(path,options=options)
```

**Comment by erezleaks** [comment]
Fix is available in version copyleaks 2.5.5
@shuklaavantika thanks for the raising the issue
